package com.fit2081.irene33624658.models

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "patients")
data class Patient(
    @PrimaryKey
    val userId: String,
    val phoneNumber: String,
    val name: String,
    val password: String = "", // Thêm trường password với giá trị mặc định
    val sex: String,
    val heifaTotalScoreMale: Double,
    val heifaTotalScoreFemale: Double,
    val discretionaryHeifaScoreMale: Double,
    val discretionaryHeifaScoreFemale: Double,
    val discretionaryServeSize: Double,
    val vegetablesHeifaScoreMale: Double,
    val vegetablesHeifaScoreFemale: Double,
    val vegetablesWithLegumesAllocatedServeSize: Double,
    val legumesAllocatedVegetables: Double,
    val vegetablesVariationsScore: Double,
    val vegetablesCruciferous: Double,
    val vegetablesTuberAndBulb: Double,
    val vegetablesOther: Double,
    val legumes: Double,
    val vegetablesGreen: Double,
    val vegetablesRedAndOrange: Double,
    val fruitHeifaScoreMale: Double,
    val fruitHeifaScoreFemale: Double,
    val fruitServeSize: Double,
    val fruitVariationsScore: Double,
    val fruitPome: Double,
    val fruitTropicalAndSubtropical: Double,
    val fruitBerry: Double,
    val fruitStone: Double,
    val fruitCitrus: Double,
    val fruitOther: Double,
    val grainsAndCerealsHeifaScoreMale: Double,
    val grainsAndCerealsHeifaScoreFemale: Double,
    val grainsAndCerealsServeSize: Double,
    val grainsAndCerealsNonWholeGrains: Double,
    val wholeGrainsHeifaScoreMale: Double,
    val wholeGrainsHeifaScoreFemale: Double,
    val wholeGrainsServeSize: Double,
    val meatAndAlternativesHeifaScoreMale: Double,
    val meatAndAlternativesHeifaScoreFemale: Double,
    val meatAndAlternativesWithLegumesAllocatedServeSize: Double,
    val legumesAllocatedMeatAndAlternatives: Double,
    val dairyAndAlternativesHeifaScoreMale: Double,
    val dairyAndAlternativesHeifaScoreFemale: Double,
    val dairyAndAlternativesServeSize: Double,
    val sodiumHeifaScoreMale: Double,
    val sodiumHeifaScoreFemale: Double,
    val sodiumMgMilligrams: Double,
    val alcoholHeifaScoreMale: Double,
    val alcoholHeifaScoreFemale: Double,
    val alcoholStandardDrinks: Double,
    val waterHeifaScoreMale: Double,
    val waterHeifaScoreFemale: Double,
    val water: Double,
    val waterTotalMl: Double,
    val beverageTotalMl: Double,
    val sugarHeifaScoreMale: Double,
    val sugarHeifaScoreFemale: Double,
    val sugar: Double,
    val saturatedFatHeifaScoreMale: Double,
    val saturatedFatHeifaScoreFemale: Double,
    val saturatedFat: Double,
    val unsaturatedFatHeifaScoreMale: Double,
    val unsaturatedFatHeifaScoreFemale: Double,
    val unsaturatedFatServeSize: Double
) {
    val heifaTotalScore: Double
        get() = if (sex == "Male") heifaTotalScoreMale else heifaTotalScoreFemale
}