//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaDotNetApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPLOMA
    {
        public int DiplomaID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> SexID { get; set; }
        public Nullable<int> TrainingTypeID { get; set; }
        public Nullable<int> TrainingProgramID { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<int> DiplomaTypeID { get; set; }
        public string BirthPlace { get; set; }
        public string VolumedBook { get; set; }
        public string DecideCode { get; set; }
        public string NumberSign { get; set; }
        public string RegisterNumber { get; set; }
        public string Language { get; set; }
        public string Colour { get; set; }
        public string Size { get; set; }
    
        public virtual DIPLOMA_TYPE DIPLOMA_TYPE { get; set; }
        public virtual RANK RANK { get; set; }
        public virtual SEX SEX { get; set; }
        public virtual TRAINING_PROGRAM TRAINING_PROGRAM { get; set; }
        public virtual TRAINING_TYPE TRAINING_TYPE { get; set; }
    }
}
