//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaDotNetApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLMMSEntities : DbContext
    {
        public DLMMSEntities()
            : base("name=DLMMSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIPLOMA> Diplomata { get; set; }
        public virtual DbSet<DIPLOMA_TYPE> DIPLOMA_TYPE { get; set; }
        public virtual DbSet<RANK> RANKs { get; set; }
        public virtual DbSet<SEX> SEXes { get; set; }
        public virtual DbSet<TRAINING_PROGRAM> TRAINING_PROGRAM { get; set; }
        public virtual DbSet<TRAINING_TYPE> TRAINING_TYPE { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
