//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaDotNetApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPLOMA_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIPLOMA_TYPE()
        {
            this.Diplomata = new HashSet<DIPLOMA>();
        }
    
        public int DiplomaTypeID { get; set; }
        public string DilomaTypeName { get; set; }
        public string OrganizationIssue { get; set; }
        public string PersonIssue { get; set; }
        public string Position { get; set; }
        public string Language { get; set; }
        public string Colour { get; set; }
        public string Size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIPLOMA> Diplomata { get; set; }
    }
}
