//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaDotNetApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_PROGRAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAINING_PROGRAM()
        {
            this.Diplomata = new HashSet<DIPLOMA>();
        }
    
        public int TrainingProgramID { get; set; }
        public string TrainingProgram { get; set; }
        public Nullable<float> MaxPoint { get; set; }
        public Nullable<float> AchievePoint { get; set; }
        public Nullable<int> Achieve { get; set; }
        public Nullable<int> TrainingTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIPLOMA> Diplomata { get; set; }
        public virtual TRAINING_TYPE TRAINING_TYPE { get; set; }
    }
}
