//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_C2203L_NguyenVanA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpID { get; set; }
        [Required]
        public string EmpName { get; set; }
        public int DeptID { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOJ { get; set; }
        [Required]
        public Nullable<bool> Gender { get; set; }
        [Required]
        [Range(1950, 2000)]
        public Nullable<int> YearOfBirth { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
