server:
  port: 8082  # The port on which the application will run

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/c2209gdoican?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true  # URL for connecting to the MySQL database
    username: root  # MySQL username
    password:  # MySQL password (fill this in if required)
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver
    initialization-mode: always  # Option to initialize the database with SQL scripts

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema; options: create, create-drop, update, validate
    show-sql: true  # Display SQL statements in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Hibernate dialect for MySQL
        format_sql: true  # Format SQL output for readability

  thymeleaf:
    cache: false  # Disable Thymeleaf cache to see changes immediately during development
