//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_C2108G2_NguyenVanA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductId { get; set; }
        [Required]
        [StringLength(32, MinimumLength =3, ErrorMessage ="Name must be 3 to 32 characters")]
        public string Name { get; set; }
        [Required]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", 
            ErrorMessage = "Price must be a numeric value.")]
        public Nullable<decimal> Price { get; set; }
        [Required]
        [Range(1, 100, ErrorMessage = "Quantity must be between 1 and 100.")]
        public Nullable<int> Quantity { get; set; }
        [Required]
        [DataType(DataType.Date)]        
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int CategoryId { get; set; }
   
        public virtual Category Category { get; set; }
    }
}
