server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/c2206ldoican?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #url: ${SPRING_DATASOURCE_URL:jdbc:mysql://ubuntu-server-01.local:3399/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Abc123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true