export default {    
    back: require('../images/icon-back.png'),
    eye: require('../images/icon-eye.png'),
    male: require('../images/icon-male.png'),
    female: require('../images/icon-female.png'),
    nonBinary: require('../images/icon-non-binary.png'),
    loseWeight: require('../images/icon-lose-weight.png'),
    buildMuscle: require('../images/icon-build-muscle.png'),
    keepFit: require('../images/icon-keep-fit.png'),
    iconBodyShapeFat: require('../images/icon-body-shape-fat.png'),
    iconBodyShapeThin: require('../images/icon-body-shape-thin.png'),
    iconBodyShapeNormal: require('../images/icon-body-shape-normal.png'),    
    iconBroccoli: require("../images/icon-broccoli.png"),
    iconSweetPotato: require("../images/icon-sweet-potato.png"),
    iconMushroom: require("../images/icon-mushroom.png"),
    iconTomato: require("../images/icon-tomato.png"),
    iconPeas: require("../images/icon-peas.png"),
    iconSpinach: require("../images/icon-spinach.png"),
    iconSucchini: require("../images/icon-zucchini.png"),
    iconPepper: require("../images/icon-pepper.png"),
}