spring:
  application:
    name: de09
  datasource:
    url: jdbc:mysql://localhost:3309/c2206ldoican?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Abc123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8088
