//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAppDotNetMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie
    {
        public int MovieId { get; set; }
        [Required]
        [StringLength(32, MinimumLength =3, ErrorMessage = "Length must be 3 to 32")]
        public string Title { get; set; }
        [Required]
        [DataType(DataType.Date, ErrorMessage = "ReleaseDate must be date type")]
        public System.DateTime ReleaseDate { get; set; }
        
        [Required]
        [Range(60, 240, ErrorMessage = "RunningTime must be 60 to 240 in length")]
        public int RunningTime { get; set; }
        [Required]
        public int GenreId { get; set; }
        
        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Box office value must be non-negative.")]
        public decimal BoxOffice { get; set; }

        public virtual Genre Genre { get; set; }
    }
}
