version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456789@
      MYSQL_DATABASE: springbootdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Abc123456789@
    networks:
      - mynetwork

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-container
    ports:
      - "8089:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
#docker-compose -f ./deployment.yml up -d