// <auto-generated />
namespace WAD_C2108G2_NguyenVanA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class insertFakedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insertFakedata));
        
        string IMigrationMetadata.Id
        {
            get { return "202303280135169_insertFakedata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
