//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_C2009i_NguyenVanB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Key]
        public int ProductId { get; set; }
        [Required]
        [StringLength(32, MinimumLength =3, ErrorMessage ="Product's name must be 3 - 32 in length")]
        public string ProductName { get; set; }
        [Required]
        public Nullable<double> Price { get; set; }
        [Required]
        public Nullable<int> Quantity { get; set; }
        [Required]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
