//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de03
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeID { get; set; }
        [Required]
        [StringLength(maximumLength: 10000, MinimumLength = 5)]
        public string EmployeeName { get; set; }
        public string DeptID { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
