server:
  port: 8090

# MySQL Connection Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/c2108g2?allowPublicKeyRetrieval=True&useSSL=false&serverTimezone=UTC
    username: root
    password: Abc123456789@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
