//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_NguyenDucAnh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage = "You must enter name")]
        [StringLength(32, ErrorMessage = "Product Name must be 3-32 in length", MinimumLength = 3)]
        public string Name { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        public Nullable<double> Price { get; set; }
        [Range(1, 100)]
        [Required]
        public Nullable<int> Quantity { get; set; }
        [DataType(DataType.DateTime)]
        [Required]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        [Required]
        public Nullable<int> CategoryId { get; set; }
    }
}
