//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_NguyenDucAnh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public int ClassId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual tblClass tblClass { get; set; }
    }
}
