//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_NguyenVanA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie
    {
        public int MovieId { get; set; }
        [Required(ErrorMessage ="You must enter movie's title")]

        [StringLength(32, MinimumLength = 3, ErrorMessage = "Title must be between 3 and 32")]
        public string Title { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        [Required(ErrorMessage = "You must enter running time")]
        [Range(60, 240, ErrorMessage ="Running time must be 60 to 240")]
        public Nullable<int> RunningTime { get; set; }
        public Nullable<int> GenreId { get; set; }
        [Required(ErrorMessage ="You must enter box office")]
        [RegularExpression("^[0-9]{1, }$", ErrorMessage = "BoxOffice must be numeric")]
        public Nullable<double> BoxOffice { get; set; }

        [Required]
        public virtual Genre Genre { get; set; }
    }
}
